虚拟键盘支持车牌号输入
Moonofweisheng/wot-design-uni pull request #529
Opened 2024-08-17 05:08 UTC by RYGRIT

### 🤔 这个 PR 的性质是？(至少选择一个)

- [ ] 日常 bug 修复
- [ x ] 新特性提交
- [ x ] 站点、文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] TypeScript 定义更新
- [ ] CI/CD 改进
- [ ] 包体积优化
- [ ] 性能优化
- [ ] 功能增强
- [ ] 国际化改进
- [ ] 代码重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他改动（是关于什么的改动？）

### 🔗 相关 Issue

[车牌号码键盘](https://github.com/Moonofweisheng/wot-design-uni/issues/353)
### 💡 需求背景和解决方案

1.虚拟键盘支持输入车牌号

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ x ] 文档已补充或无须补充
- [ x ] 代码演示已提供或无须提供
- [ x ] TypeScript 定义已补充或无须补充

2024-08-19 13:58 UTC, Moonofweisheng requested changes
感谢你的PR！  
我想我们应当提供一个不产生破坏性更新的车牌号键盘组件，否则组件的使用者将不得不从`number-keyboard`迁移至`keyboard`

2024-08-19 14:46 UTC, RYGRIT commented
> > 那我重新加一个 car-keyword 组件 这样可以吗
> 
> 我想我们可以这样，在保留number- keyboard的同时，提供keyboard组件，keyboard可以提供`number`和`car`模式，未来可以废弃掉`number-keyboard`。

好的好的 周末我重新提一个

2024-08-30 06:33 UTC, RYGRIT commented
> > 那我重新加一个 car-keyword 组件 这样可以吗
> 
> 我想我们可以这样，在保留number- keyboard的同时，提供keyboard组件，keyboard可以提供`number`和`car`模式，未来可以废弃掉`number-keyboard`。

我已完成新的PR，不知道能否符合要求

2024-08-30 06:35 UTC, closed without merging

2024-08-30 08:34 UTC, Moonofweisheng commented
好的，已收到，我会尽快review。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Moonofweisheng/wot-design-uni"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月30日(星期五) 下午2:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Moonofweisheng/wot-design-uni] feat: ✨ Keyboard 虚拟键盘支持车牌号输入 (PR #529)





   
那我重新加一个 car-keyword 组件 这样可以吗
  
我想我们可以这样，在保留number- keyboard的同时，提供keyboard组件，keyboard可以提供number和car模式，未来可以废弃掉number-keyboard。
  
我已完成新的PR，不知道能否符合要求
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;